/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 一括ダウンロードのファイル一覧
         * @description 取り扱う範囲の全施設（廃止を含む）を、都道府県ごとと全体（`all`）の CSV / JSON Lines（gzip 圧縮）で提供します。
         *     毎日の取込の後に、データが変わっていれば作り直します。JSON Lines の各行は施設詳細と同じ形です。
         *     CSV はコードと名前を別の列にし、診療科目は `|` 区切り、`designation_history` と `bed_counts` は JSON 文字列です。
         *     `sha256` でダウンロードしたファイルを検証できます。以降の差分は、一覧APIの `updated_since` で取得してください。
         */
        get: operations["v1.exports.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exports/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 一括ダウンロード
         * @description ファイル一覧の `url` からダウンロードします。`ETag`（SHA-256）と `If-None-Match` で、変わっていなければ 304 を返します。
         */
        get: operations["v1.exports.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/medical-facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 施設一覧・検索
         * @description 医療施設マスタをページネーション付きで返します。`q` は施設名・住所の全角半角/異体字ゆれを
         *     吸収したあいまい検索です。`latitude`・`longitude` を指定すると、`radius` 以内の施設を近い順に返します。
         */
        get: operations["v1.medical-facilities.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/medical-facilities/{medicalFacility}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 施設詳細
         * @description idを指定して医療施設マスタの1件を返します。
         */
        get: operations["v1.medical-facilities.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/medical-facilities/{medicalFacility}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 施設の履歴
         * @description 1つの施設の新規・廃止・変更を新しい順に返します。取込を始めた時点で掲載されていた施設は、
         *     最も古い記録が `origin` = 初回取込 の「新規」になります（開業日ではありません）。
         */
        get: operations["v1.medical-facilities.events.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/medical-facility-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 変化の一覧
         * @description 毎月の公開データを比較して見つかった、施設の新規・廃止・変更を新しい順に返します。
         *     `occurred_on` は変化が載った公開データの日付で、実際の開業日・廃止日ではありません。
         *     取込を始めた時点のデータ（初回取込）と、取り込み直しによる差分（再処理）は含みません。
         */
        get: operations["v1.medical-facility-events.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 絞り込みの選択肢
         * @description 一覧APIの絞り込み条件に使える値と、その日本語名を返します。`code` はそのまま各パラメータに渡せます。
         *     都道府県・地方厚生局・施設種別は、このAPIが取り扱う範囲のものだけを返します。
         *     `designation_reasons` は元データでは自由記述のため、代表的な値のみです。
         */
        get: operations["v1.options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DepartmentBaseCategory
         * @description Coarse "which specialty family" classification for a facility's standing 診療科目 (departments), derived from Japan's officially permitted 標榜診療科名 base categories (医療法施行規則). The source data allows open-ended qualifier+base-category combination naming (e.g. "糖尿病・脂質代謝内科" = a qualifier + 内科), so exact department-name fidelity is not attempted here -- only which of these ~26 base categories a department name matches, via marker/substring matching in DepartmentCategoryClassifier. This provisional case list is derived from real-data research (recovers 96.3% of observed department-token occurrences); it may be adjusted once Phase A-2's Hokkaido spike confirms the final observed vocabulary.
         * @enum {integer}
         */
        DepartmentBaseCategory: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26;
        /**
         * InstitutionType
         * @enum {integer}
         */
        InstitutionType: 1 | 2 | 3 | 4;
        /** MedicalFacilityEventResource */
        MedicalFacilityEventResource: {
            id: number;
            event_type: {
                code: number;
                label: string;
            };
            origin: {
                code: number;
                label: string;
            };
            /** @description 変化が載った公開データの日付（実際の開業・廃止・変更の日ではない） */
            occurred_on: string;
            /** @description 過去に廃止された施設が再び掲載されたか（新規のときのみ） */
            is_reopening?: boolean;
            /** @description 変更された項目と変更前後の値（変更のときのみ） */
            changes?: {
                attribute: string | "bureau";
                old: {
                    code: number;
                    label: string;
                } | unknown[] | string | null;
                new: {
                    code: number;
                    label: string;
                } | unknown[] | string | null;
            }[];
            facility?: components["schemas"]["MedicalFacilityResource"];
        };
        /**
         * MedicalFacilityEventType
         * @enum {integer}
         */
        MedicalFacilityEventType: 1 | 2 | 3;
        /** MedicalFacilityResource */
        MedicalFacilityResource: {
            id: number;
            facility_code: string;
            /** @description 全国で一意な10桁の医療機関コード（都道府県番号＋点数表番号＋医療機関コード7桁） */
            medical_institution_code: string | null;
            institution_type: {
                code: number | string;
                label: string;
            };
            status: {
                code: number | string;
                label: string;
            };
            bureau: {
                code: number | string;
                label: string;
            };
            name: string;
            prefecture_code: string;
            prefecture: {
                code: number | string;
                label: string;
            };
            /** @description 住所から判定した市区町村。判定できない場合はnull */
            municipality: {
                code: string | null;
                label: string;
            } | null;
            postal_code: string | null;
            address: string;
            /**
             * @description 住所から求めた座標（世界測地系）。`level` はその精度（住居・街区・地番・町丁目など）。
             *     求められなかった施設はnull
             */
            location: {
                latitude: number;
                longitude: number;
                level: {
                    code: number | string;
                    label: string;
                };
            } | null;
            /** @description 検索地点からの距離（メートル）。`latitude`・`longitude` を指定した検索のときだけ含まれる */
            distance?: number;
            phone_number: string | null;
            designated_on: string | null;
            designation_history: unknown[] | null;
            bed_counts: unknown[] | null;
            department_categories: {
                code: number | string;
                label: string;
            }[] | string[];
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * MedicalFacilityStatus
         * @enum {integer}
         */
        MedicalFacilityStatus: 1 | 2 | 3;
        /**
         * Prefecture
         * @description The 47 prefectures by JIS X 0401 code, the form prefecture_code is stored and filtered in.
         * @enum {string}
         */
        Prefecture: "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" | "19" | "20" | "21" | "22" | "23" | "24" | "25" | "26" | "27" | "28" | "29" | "30" | "31" | "32" | "33" | "34" | "35" | "36" | "37" | "38" | "39" | "40" | "41" | "42" | "43" | "44" | "45" | "46" | "47";
        /**
         * RhbBureau
         * @description The 8 regional health bureaus (地方厚生局) that each independently publish their own jurisdiction's insured medical institution list.
         * @enum {integer}
         */
        RhbBureau: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "v1.exports.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            generated_at: string;
                            /** @description ファイルに含まれる施設のうち、最も新しい `updated_at`。差分の同期の起点に使える */
                            data_updated_at: string;
                            files: unknown[];
                        };
                        meta: {
                            attribution: {
                                /** @constant */
                                notice: "本APIのデータは、各地方厚生局が公開する「保険医療機関・保険薬局の指定一覧」を加工して作成しています。";
                                license: {
                                    /** @constant */
                                    name: "公共データ利用規約（第1.0版）";
                                    /** @constant */
                                    url: "https://www.digital.go.jp/resources/open_data/public_data_license_v1.0";
                                };
                                /** @constant */
                                disclaimer: "データの正確性・完全性は保証しません。最新かつ正確な情報は、各地方厚生局の公表資料を確認してください。";
                                /** @description 市区町村・座標の出典（デジタル庁 アドレス・ベース・レジストリ、CC BY 4.0）。 */
                                address_source: {
                                    /** @constant */
                                    name: "アドレス・ベース・レジストリ（デジタル庁）の市区町村・町字・住居表示・地番の各マスターと位置参照データを加工して作成";
                                    /** @constant */
                                    url: "https://catalog.registries.digital.go.jp/rc/dataset/";
                                };
                                /** @description The bureaus this installation actually draws from (RhbScope). */
                                sources: {
                                    bureau: string;
                                    url: string;
                                }[];
                            };
                        };
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "一括ダウンロードのファイルはまだ作成されていません。";
                    };
                };
            };
        };
    };
    "v1.exports.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @example attachment */
                    "Content-Disposition": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "ファイルが見つかりません。";
                    };
                };
            };
        };
    };
    "v1.medical-facilities.index": {
        parameters: {
            query?: {
                /** @description 都道府県コード（JIS X 0401の2桁、01〜47） */
                prefecture_code?: components["schemas"]["Prefecture"];
                /** @description 市区町村コード（全国地方公共団体コード5桁。例: 13101 千代田区）。住所から判定した値で、判定できない施設は含まれない */
                municipality_code?: string;
                /** @description 施設種別 */
                institution_type?: components["schemas"]["InstitutionType"];
                /** @description 指定状態 */
                status?: components["schemas"]["MedicalFacilityStatus"];
                /** @description 発行元の地方厚生局 */
                bureau_code?: components["schemas"]["RhbBureau"];
                /** @description 診療科目の大分類 */
                department_category?: components["schemas"]["DepartmentBaseCategory"];
                /**
                 * @description 10桁の医療機関コード（都道府県番号＋点数表番号＋医療機関コード7桁）。
                 *     カンマ区切りで最大100件まで指定できる
                 */
                medical_institution_code?: string;
                /** @description 施設名・住所のあいまい検索キーワード（全角半角・異体字ゆれを吸収） */
                q?: string;
                /** @description 指定年月日がこの日以降（YYYY-MM-DD） */
                designated_from?: string;
                /** @description 指定年月日がこの日以前（YYYY-MM-DD） */
                designated_to?: string;
                /**
                 * @description 登録理由（`designation_history` の `reason`）。例: 新規、交代、組織変更、移転。
                 *     指定年月日と組み合わせると「期間内に新規開業した施設」を取得できる
                 */
                designation_reason?: string;
                /**
                 * @description 並び順。`designated_on` / `-designated_on`（指定年月日の古い順 / 新しい順、指定年月日のない施設は末尾）、
                 *     `updated_at` / `-updated_at`（内容が変わった日時の古い順 / 新しい順）。省略時はid順
                 */
                sort?: "id" | "designated_on" | "-designated_on" | "updated_at" | "-updated_at";
                /**
                 * @description この日時以降に内容が変わった施設だけを返す（ISO 8601、例: 2026-10-01T05:00:00Z）。
                 *     廃止・再開も含む。差分の同期には `sort=updated_at` と組み合わせる
                 */
                updated_since?: string;
                /**
                 * @description 検索地点の緯度（世界測地系）。`longitude` と組み合わせ、`radius` 以内の施設を近い順に返す
                 *     （`sort` を指定した場合はその順）。各施設に `distance` が付く
                 */
                latitude?: number;
                /** @description 検索地点の経度（世界測地系） */
                longitude?: number;
                /** @description 検索半径（メートル、デフォルト1000、最大20000）。`latitude`・`longitude` と組み合わせる */
                radius?: number;
                /** @description 1ページあたりの件数（デフォルト25、最大100） */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `MedicalFacilityResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MedicalFacilityResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                            attribution: {
                                /** @constant */
                                notice: "本APIのデータは、各地方厚生局が公開する「保険医療機関・保険薬局の指定一覧」を加工して作成しています。";
                                license: {
                                    /** @constant */
                                    name: "公共データ利用規約（第1.0版）";
                                    /** @constant */
                                    url: "https://www.digital.go.jp/resources/open_data/public_data_license_v1.0";
                                };
                                /** @constant */
                                disclaimer: "データの正確性・完全性は保証しません。最新かつ正確な情報は、各地方厚生局の公表資料を確認してください。";
                                /** @description 市区町村・座標の出典（デジタル庁 アドレス・ベース・レジストリ、CC BY 4.0）。 */
                                address_source: {
                                    /** @constant */
                                    name: "アドレス・ベース・レジストリ（デジタル庁）の市区町村・町字・住居表示・地番の各マスターと位置参照データを加工して作成";
                                    /** @constant */
                                    url: "https://catalog.registries.digital.go.jp/rc/dataset/";
                                };
                                /** @description The bureaus this installation actually draws from (RhbScope). */
                                sources: {
                                    bureau: string;
                                    url: string;
                                }[];
                            };
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.medical-facilities.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The medical facility ID */
                medicalFacility: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `MedicalFacilityResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MedicalFacilityResource"];
                        meta: {
                            attribution: {
                                /** @constant */
                                notice: "本APIのデータは、各地方厚生局が公開する「保険医療機関・保険薬局の指定一覧」を加工して作成しています。";
                                license: {
                                    /** @constant */
                                    name: "公共データ利用規約（第1.0版）";
                                    /** @constant */
                                    url: "https://www.digital.go.jp/resources/open_data/public_data_license_v1.0";
                                };
                                /** @constant */
                                disclaimer: "データの正確性・完全性は保証しません。最新かつ正確な情報は、各地方厚生局の公表資料を確認してください。";
                                /** @description 市区町村・座標の出典（デジタル庁 アドレス・ベース・レジストリ、CC BY 4.0）。 */
                                address_source: {
                                    /** @constant */
                                    name: "アドレス・ベース・レジストリ（デジタル庁）の市区町村・町字・住居表示・地番の各マスターと位置参照データを加工して作成";
                                    /** @constant */
                                    url: "https://catalog.registries.digital.go.jp/rc/dataset/";
                                };
                                /** @description The bureaus this installation actually draws from (RhbScope). */
                                sources: {
                                    bureau: string;
                                    url: string;
                                }[];
                            };
                        };
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "v1.medical-facilities.events.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The medical facility ID */
                medicalFacility: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `MedicalFacilityEventResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MedicalFacilityEventResource"][];
                        meta: {
                            attribution: {
                                /** @constant */
                                notice: "本APIのデータは、各地方厚生局が公開する「保険医療機関・保険薬局の指定一覧」を加工して作成しています。";
                                license: {
                                    /** @constant */
                                    name: "公共データ利用規約（第1.0版）";
                                    /** @constant */
                                    url: "https://www.digital.go.jp/resources/open_data/public_data_license_v1.0";
                                };
                                /** @constant */
                                disclaimer: "データの正確性・完全性は保証しません。最新かつ正確な情報は、各地方厚生局の公表資料を確認してください。";
                                /** @description 市区町村・座標の出典（デジタル庁 アドレス・ベース・レジストリ、CC BY 4.0）。 */
                                address_source: {
                                    /** @constant */
                                    name: "アドレス・ベース・レジストリ（デジタル庁）の市区町村・町字・住居表示・地番の各マスターと位置参照データを加工して作成";
                                    /** @constant */
                                    url: "https://catalog.registries.digital.go.jp/rc/dataset/";
                                };
                                /** @description The bureaus this installation actually draws from (RhbScope). */
                                sources: {
                                    bureau: string;
                                    url: string;
                                }[];
                            };
                        };
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "v1.medical-facility-events.index": {
        parameters: {
            query?: {
                /** @description 変化の種類（1: 新規 / 2: 廃止 / 3: 変更） */
                event_type?: components["schemas"]["MedicalFacilityEventType"];
                /** @description 変化が載った公開データの日付がこの日以降（YYYY-MM-DD） */
                occurred_from?: string;
                /** @description 変化が載った公開データの日付がこの日以前（YYYY-MM-DD） */
                occurred_to?: string;
                /** @description 施設の都道府県コード（JIS X 0401の2桁、01〜47） */
                prefecture_code?: components["schemas"]["Prefecture"];
                /** @description 施設の種別 */
                institution_type?: components["schemas"]["InstitutionType"];
                /** @description 1ページあたりの件数（デフォルト25、最大100） */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `MedicalFacilityEventResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["MedicalFacilityEventResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                            attribution: {
                                /** @constant */
                                notice: "本APIのデータは、各地方厚生局が公開する「保険医療機関・保険薬局の指定一覧」を加工して作成しています。";
                                license: {
                                    /** @constant */
                                    name: "公共データ利用規約（第1.0版）";
                                    /** @constant */
                                    url: "https://www.digital.go.jp/resources/open_data/public_data_license_v1.0";
                                };
                                /** @constant */
                                disclaimer: "データの正確性・完全性は保証しません。最新かつ正確な情報は、各地方厚生局の公表資料を確認してください。";
                                /** @description 市区町村・座標の出典（デジタル庁 アドレス・ベース・レジストリ、CC BY 4.0）。 */
                                address_source: {
                                    /** @constant */
                                    name: "アドレス・ベース・レジストリ（デジタル庁）の市区町村・町字・住居表示・地番の各マスターと位置参照データを加工して作成";
                                    /** @constant */
                                    url: "https://catalog.registries.digital.go.jp/rc/dataset/";
                                };
                                /** @description The bureaus this installation actually draws from (RhbScope). */
                                sources: {
                                    bureau: string;
                                    url: string;
                                }[];
                            };
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "v1.options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            prefectures: unknown[];
                            institution_types: unknown[];
                            statuses: unknown[];
                            bureaus: unknown[];
                            department_categories: unknown[];
                            event_types: unknown[];
                            geocode_levels: unknown[];
                            designation_reasons: [
                                "新規",
                                "組織変更",
                                "交代",
                                "移動",
                                "移転",
                                "その他",
                                "継承"
                            ];
                        };
                    };
                };
            };
        };
    };
}
